const data= {
    "info":{
        "_postman_id":"c2686870-5c13-4f20-a4f4-acad30115e94",
        "name":"Renews18",
        "schema":"https://schema.getpostman.com/json/collection/v2.0.0/collection.json"},
        "item":[
            {
                "name":"City List",
                "id":"8ef5f5d5-a14d-4c46-89b5-569862979a06",
                "protocolProfileBehavior":{
                    "disableBodyPruning":true
                },
                "request":{
                    "method":"GET",
                    "header":[],
                    "body":{
                        "mode":"formdata",
                        "formdata":[
                            {
                                "key":"city_id",
                                "value":"1",
                                "type":"text"
                            },
                            {
                                "key":"service_id",
                                "value":"1",
                                "type":"text"
                            }
                        ]
                    },
                    "url":"http://renews18.com/api/city_list"
                },
                "response":[]
            },
            {
                "name":"services list",
                "id":"b2017865-6c32-4149-ac14-737e630c1750",
                "protocolProfileBehavior":{
                    "disableBodyPruning":true
                },
                "request":{
                    "method":"GET",
                    "header":[],
                    "body":{
                        "mode":"formdata",
                        "formdata":[
                            {
                                "key":"city_id",
                                "value":"1",
                                "type":"text"
                            },
                            {
                                "key":"service_id",
                                "value":"1",
                                "type":"text"
                            }
                        ]
                    },
                    "url":"http://127.0.0.1:8000/api/service_list"
                },
                "response":[]
            },
            {
                "name":"Employee List",
                "id":"f0af4416-261f-423f-b547-fbfe4cc58820",
                "request":{
                    "method":"POST",
                    "header":[],
                    "body":{
                        "mode":"formdata",
                        "formdata":[
                            {
                                "key":"city_id",
                                "value":"1",
                                "type":"text"
                            },
                            {
                                "key":"service_id",
                                "value":"4",
                                "type":"text"
                            }
                        ]
                    },
                    "url":"http://127.0.0.1:8000/api/employee_list"
                },
                "response":[]
            },
            {
                "name":"newspaper list",
                "id":"31681c21-a97a-43a0-a377-1f9211fe2fa3",
                "protocolProfileBehavior":{
                    "disableBodyPruning":true
                },
                "request":{
                    "method":"GET",
                    "header":[],
                    "body":{
                        "mode":"formdata",
                        "formdata":[
                            {
                                "key":"city_id",
                                "value":"1",
                                "type":"text"
                            },
                            {
                                "key":"service_id",
                                "value":"1",
                                "type":"text"
                            }
                        ]
                    },
                    "url":"http://127.0.0.1:8000/api/newspaper_list"
                },
                "response":[]
            },
            {
                "name":"videos link list","id":"74f12ef4-e79b-4fd8-bffa-de842123e9b3","protocolProfileBehavior":{"disableBodyPruning":true},"request":{"method":"GET","header":[],"body":{"mode":"formdata","formdata":[{"key":"city_id","value":"1","type":"text"},{"key":"service_id","value":"1","type":"text"}]},"url":"http://127.0.0.1:8000/api/headline_list"},"response":[]},{"name":"headline list","id":"5fc28317-d399-4ab0-9830-134bbbca3786","protocolProfileBehavior":{"disableBodyPruning":true},"request":{"method":"GET","header":[],"body":{"mode":"formdata","formdata":[{"key":"city_id","value":"1","type":"text"},{"key":"service_id","value":"1","type":"text"}]},"url":"http://127.0.0.1:8000/api/headline_list"},"response":[]}]}